{% set name = "spyder-terminal" %}
{% set version = "0.3.0" %}
{% set hash_type = "sha256" %}
{% set hash = "0191fa98940d8505683b68534bde119c6ff676c21f8d5f921d15f422a8247301" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - spyder >=4.0.0,<5.0.0
    - tornado
    - terminado
    - coloredlogs
    - requests

test:
  imports:
    - spyder_terminal  # [not linux]

about:
  home: https://github.com/spyder-ide/spyder-terminal
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Spyder plugin for displaying system terminals.
  description: |
    This plugin allows you to execute flawlessly any bash command
    inside Spyder, even ncurses applications like nano or vi, or
    Windows console applications such as powershell.
  dev_url: https://github.com/spyder-ide/spyder-terminal

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - goanpeca
