{% set name = "spyder-terminal" %}
{% set version = "1.2.2" %}
{% set hash = "34235070276a0cb255a5c371cbef076a355059a8a8c71fa9805df229ea0335da" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - spyder >=5.2.0
    - tornado
    - terminado
    - coloredlogs
    - requests

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  # Importing spyder_terminal requires many CDTs to be installed on linux
  # This would needlessly increase build time
  # imports:
  #   - spyder_terminal

about:
  home: https://github.com/spyder-ide/spyder-terminal
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Spyder plugin for displaying system terminals.
  description: |
    This plugin allows you to execute flawlessly any bash command
    inside Spyder, even ncurses applications like nano or vi, or
    Windows console applications such as powershell.
  dev_url: https://github.com/spyder-ide/spyder-terminal

extra:
  recipe-maintainers:
    - CAM-Gerlach
    - andfoy
    - ccordoba12
    - steff456
