{% set name = "spyder-terminal" %}
{% set version = "0.2.4" %}
{% set hash_type = "sha256" %}
{% set hash = "e83147c8a25123ed99baa0da17ed58318a442aad18d1bdf6815c7ee899910c10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 1000
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - coloredlogs
    - pexpect  # [not win]
    - python
    - pywinpty  # [win]
    - requests
    - spyder >=3.2
    - tornado

test:
  imports:
    - spyder_terminal  # [not osx]

about:
  home: https://github.com/spyder-ide/spyder-terminal
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Spyder plugin for displaying system terminals.
  description: |
    This plugin allows you to execute flawlessly any bash command
    inside Spyder, even ncurses applications like nano or vi, or
    Windows console applications such as powershell.
  dev_url: https://github.com/spyder-ide/spyder-terminal

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - goanpeca
