{% set name = "spyder-terminal" %}
{% set version = "0.2.1" %}
{% set hash_type = "sha256" %}
{% set hash = "e1f21a1a2ff5e87d7e42d3617dc45a2a1e52a2446dc271bedf07b476b43df19c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  skip: True  # [win and py27]
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - coloredlogs
    - pexpect
    - python
    - pywinpty  # [win]
    - requests
    - spyder >=3.2
    - tornado

test:
  imports:
    - spyder_terminal

about:
  home: https://github.com/spyder-ide/spyder-terminal
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Spyder plugin for displaying system terminals.
  description: |
    This plugin allows you to execute flawlessly any bash command
    inside Spyder, even ncurses applications like nano or vi, or
    Windows console applications such as powershell.
  dev_url: https://github.com/spyder-ide/spyder-terminal

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - goanpeca
