appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '38'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DGFB0nnBg5stp/8muy9jCgDkX8vD8c7tpz0BSpmyUK62WeyEsDdR+0LwiKZgCy1QBFMRHWFpSL+FUTAD31JOyh0tQnCgZMmMcqTRxCacnVKlhWvQs9rR4ZSDEUNuImE4Q+5CjSpkJbZUHydH+iQwbYS5vHIyqtABb/mGUlTJ1NVlGOaGh+VN/Y7kMo669ErBKJBPoiWKrc7nmMRjJIBuKcpjQJWSAtsIGCAnurM9h6CvinUpLZtVzgG96ocvC/EMPwVZWNOQgmXaengvCSCj/vxWroc3zeO70KBiK4sY3ffez+C7RrZBs0PK9L0jaIxUbrix/QNGYAanOYHZm530cguKQ8r1ARNdIS84/nzBowlC4/u8zUF08smpXCYqIRbI6mexHnkDYml7pASQAfUlAYnB8VVHgOCDJHVCnVO5o4kGzXohoAfue5V2HivKIOR3vESt6EmfKzOvyCWtV5dqS3QcrYqwffUiRcZjH0vDuD/9+XSdmBh6NeC65QQxW/GXfQLFfMx/GSNMjPW8GwCq1HJxp/vbkXAEWsK7Ayf3nIeAx4x2O6UcNRCmdj3kJqVj7NwX0Db2s5P5DBxnb21iztHw9vAgyf9x6QEltzTABoCmFrn7qvmG+9vBxZHOw+k1zJ9OBQmtFyf4kvVqG8+SN3uMXDSq9m8fo2ousR8FTj8=}
